adults:
  name: Adult devices
  entities:
    - device_tracker.michaels_iphone
    - device_tracker.karens

kids:
  name: Kid devices
  entities:
    - device_tracker.iphone
    - device_tracker.a0edcd82b52e

devices:
  name: Devices
  entities:
    - device_tracker.0403d6dab4bc
    - device_tracker.v60ws

dclxvi_pi:
  name: DCLXVI Tracker
  entities:
    - camera.dclxvi_windshield_image
    - binary_sensor.dclxvi_connection_status
    - device_tracker.dclxvi_pi
    - light.v60_status_bulb
    - automation.v60_check_bulb
    - automation.v60_engine_start_switch
    - automation.v60_engine_is_not_running
    - automation.v60_engine_is_running
    - automation.v60_tracker_is_online
    - automation.v60_tracker_is_offline
    - automation.v60_tracker_arrives_home
    - automation.v60_voc_is_home
    - automation.v60_is_unlocked

litterboxes:
  name: Litter Boxes
  entities:
    - light.tradfri_transformer_10w_2
    - light.tradfri_transformer_10w

pets:
  name: Pets
  entities:
    - group.litterboxes
    - sensor.litter_box_blue
    - light.tradfri_transformer_10w_2
    - sensor.litter_box_grey
    - light.tradfri_transformer_10w
    - switch.aquarium
    - light.kitchen_aquarium

#travel:
#  name: Travel Time
#  entities:
#    - sensor.to_ericsson
#    - sensor.to_ericsson_diff
#    - sensor.to_crites__riddell
#    - sensor.to_crites__riddell_diff
#    - sensor.from_ericsson
#    - sensor.from_ericsson_diff
#    - sensor.from_crites__riddell
#    - sensor.from_crites__riddell_diff
#    - sensor.dclxvi_to_home
#    - sensor.to_home_dclxvi_diff

kitchen:
  name: Kitchen
  entities:
    - light.kitchen_1
    - light.kitchen_2
    - light.kitchen_3
    - light.tradfri_transformer_10w_3
    - sensor.skrubb

otterstedt:
  name: Michael
  entities:
    - device_tracker.michaels_iphone
    - binary_sensor.work_day
    - !secret gmail_entity_id
 #   - binary_sensor.gmail_rising
 #   - sensor.to_ericsson
 #   - sensor.to_ericsson_diff
 #   - sensor.from_ericsson
 #   - sensor.from_ericsson_diff
 #   - sensor.dclxvi_to_home
 #   - sensor.to_home_dclxvi_diff

fraser:
  name: Karen
  entities:
    - device_tracker.karens
#    - sensor.to_crites__riddell
#    - sensor.to_crites__riddell_diff
#    - sensor.from_crites__riddell
#    - sensor.from_crites__riddell_diff