- id: motion_detected_basement_door
  alias: Basement Front Door Motion
  trigger:
    entity_id: light.approach_lamp
    platform: state
    to: 'on'
  condition: 
    - condition: template
      value_template: "{{ not is_state('media_player.chambre_principale', 'playing') }}"
  action:
    - service: camera.play_stream
      data:
        entity_id: camera.amcrest_camera
        media_player: media_player.chambre_principale
    - service: mqtt.publish
      data:
        payload: on
        topic: "hass/message/motiondetector/sln/basement/front"
    - service: notify.pushover
      data:
        message: "Motion Detected Silverlyckan: Basement Front"
        title: "Motion Silverlyckan"

- id: sunset_lights
  alias: Lights at sunset
  trigger:
    platform: sun
    event: sunset
    offset: "-00:15:00"
  condition:
    - condition: state
      entity_id: person.dclxvi
      state: home
  action:
    - service: switch.turn_on
      entity_id: switch.balcony_power
      
- id: sunrise_lights
  alias: Lights at sunrise
  trigger:
    platform: sun
    event: sunrise
    offset: "00:15:00"
  condition:
    - condition: state
      entity_id: person.dclxvi
      state: home
  action:
    - service: switch.turn_off
      entity_id: switch.balcony_power

- id: '1579890137263'
  alias: Car arrives
  description: ''
  trigger:
  - entity_id: person.dclxvi
    platform: state
    from: "not_home"
    to: "home"
  condition: []
  action:
  - device_id: 922a41c5784946e0954cc5ac8fab4967
    domain: light
    entity_id: light.approach_lamp
    type: turn_on
  - device_id: 1fe3978e532041e980d3e7535970d390
    domain: light
    entity_id: light.basement_outdoor_lamp
    type: turn_on
  - device_id: 5099556d121a4953914419fa2db47a5c
    domain: switch
    entity_id: switch.balcony_power
    type: turn_on
- id: '1581717740537'
  alias: Karen arrives
  description: ''
  trigger:
  - entity_id: person.karen
    platform: state
    from: "not_home"
    to: "home"
  condition: []
  action:
  - delay: 00:03:00
  - entity_id: script.goat4sale_sous_sol
    service: script.turn_on

- alias: 'Silver Flight entry notification'
  trigger:
    platform: event
    event_type: opensky_entry
  action:
    - service: mqtt.publish
      data_template:
        payload_template: "{{ trigger.event.data.callsign }}"
        topic: "hass/message/silversky/callsign"
        retain: true
    - service: notify.pushover
      data_template:
        message: "Flyover by: {{ trigger.event.data.callsign }}"
        title: "{{ trigger.event.data.callsign }}"
        data:
          url: "https://flightaware.com/live/flight/{{ trigger.event.data.callsign }}"
          sound: pianobar
          priority: 0
          attachment: "https://w0.pngwave.com/png/942/542/airplane-computer-icons-graphy-aircraft-png-clip-art.png"
    - service: notify.slack
      data_template:
        message: "Silverlyckan Flyover by: {{ trigger.event.data.callsign }} - https://flightaware.com/live/flight/{{ trigger.event.data.callsign }}"
        title: "{{ trigger.event.data.callsign }}"

