 
# Configure a default setup of Home Assistant (frontend, api, etc) 
default_config: 
 
# Uncomment this if you are using SSL/TLS, running in Docker container, etc. 
# http: 
#   base_url: example.duckdns.org:8123

homeassistant:
  unit_system: metric
  time_zone: America/Montreal
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password
      api_password: !secret http_api_password
 
 
amcrest: 
  - host: 10.0.1.52 
    username: admin 
    password: !secret mqtt_password 
    binary_sensors:
      - motion_detected
      - online
    sensors:
      - sdcard
      - ptz_preset
#  - host: 10.0.1.54 
#    username: admin 
#    password: !secret mqtt_password 
#    binary_sensors:
#      - motion_detected
#      - online
#    sensors:
#      - sdcard
#      - ptz_preset

camera:
  - platform: mjpeg
    name: !secret camera_sln_washer_name
    mjpeg_url: !secret camera_sln_washer_url
    
climate:
  - platform: generic_thermostat
    name: Bedroom Thermostat
    heater: switch.radiator_bedroom
    target_sensor: sensor.bedroom_sln_temperature
    max_temp: 24
    cold_tolerance: 0.8
    keep_alive:
      minutes: 5

device_tracker: 
  - platform: bluetooth_tracker 
  - platform: bluetooth_le_tracker 
    track_new_devices: true 
  - platform: nmap_tracker 
    hosts: 10.0.1.0/24 
    home_interval: 10 
    consider_home: 180
  - platform: tile
    username: !secret tile_username
    password: !secret tile_password
    
discovery:

gdacs:

geo_location:
  - platform: usgs_earthquakes_feed
    feed_type: 'past_month_all_earthquakes'
    radius: 50
    minimum_magnitude: 0.0

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret
 
influxdb: 

media_extractor:
 
mqtt: 
  broker: !secret mqtt_host 
  port: !secret mqtt_port 
  username: !secret mqtt_user 
  password: !secret mqtt_password 
  certificate: /etc/ssl/certs/ca-certificates.crt 
 
mqtt_statestream: 
  base_topic: hass/statestream 
  publish_attributes: true 
  publish_timestamps: true

mqtt_eventstream:
  publish_topic: hass/eventstream/slaves/sln
  subscribe_topic: hass/eventstream/master

plex:
  host: 10.0.1.2
  port: 32401

prometheus:
  namespace: hass_sln

sensor:
  - platform: season
    name: Season
  - platform: mqtt
    name: Silver Callsign
    unique_id: silversky_callsign
    state_topic: "hass/message/silversky/callsign"
  - platform: opensky
    radius: 15
    name: silversky
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'
  - platform: template
    sensors:
      timetopoubelle:
        friendly_name: Days to Poubelle
        entity_id: sensor.time
        value_template: >-
          {% if states.calendar.marbleton_poubelle.attributes.start_time %}
            {{((as_timestamp(states.calendar.marbleton_poubelle.attributes.start_time) - as_timestamp(states('sensor.date_time_iso')) ) / ( 60 * 60 * 24 ) ) | default(99) | round(2, 'common') }}
          {%- else -%}
            0
          {%- endif %}
      timetorecyclage:
        friendly_name: Days to Recyclage
        entity_id: sensor.time
        value_template: >-
          {% if states.calendar.marbleton_recyclage.attributes.start_time %}
            {{((as_timestamp(states.calendar.marbleton_recyclage.attributes.start_time) - as_timestamp(states('sensor.date_time_iso')) ) / ( 60 * 60 * 24 ) ) | default(99) | round(2, 'common') }}
          {%- else -%}
            0
          {%- endif %}
      bishoptonpoubelle:
        friendly_name: Days to Poubelle - Bishopton
        entity_id: sensor.time
        value_template: >-
          {% if states.calendar.bishopton_poubelle.attributes.start_time %}
            {{((as_timestamp(states.calendar.bishopton_poubelle.attributes.start_time) - as_timestamp(states('sensor.date_time_iso')) ) / ( 60 * 60 * 24 ) ) | default(99) | round(2, 'common') }}
          {%- else -%}
            0
          {%- endif %}
      bishoptonrecyclage:
        friendly_name: Days to Recyclage - Bishopton
        entity_id: sensor.time
        value_template: >-
          {% if states.calendar.bishopton_recyclage.attributes.start_time %}
            {{((as_timestamp(states.calendar.bishopton_recyclage.attributes.start_time) - as_timestamp(states('sensor.date_time_iso')) ) / ( 60 * 60 * 24 ) ) | default(99) | round(2, 'common') }}
          {%- else -%}
            0
          {%- endif %}
      timetocomposte:
        friendly_name: Days to Composte
        entity_id: sensor.time
        value_template: >-
          {% if states.calendar.dudswell_composte.attributes.start_time %}
            {{((as_timestamp(states.calendar.dudswell_composte.attributes.start_time) - as_timestamp(states('sensor.date_time_iso')) ) / ( 60 * 60 * 24 ) ) | default(99) | round(2, 'common') }}
          {%- else -%}
            0
          {%- endif %}

speedtestdotnet:

tellduslive:
  host: 10.0.1.25

# Text to speech
tts:
  - platform: google_translate

upnp:
  sensors: true
  port_mapping: false

volvooncall:
  username: !secret voc_user
  password: !secret voc_password
  region: !secret voc_region
  resources:
    - position 
    - engine_start
    - heater
    - is_engine_running
    - lock
    - fuel_amount
    - fuel_amount_level
    - distance_to_empty
    - battery_range
    - battery_level
    - any_door_open
    - any_window_open

wwlln:
  radius: 50

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
