adults:
  name: Adult devices
  entities:
    - person.michael
    - person.karen

kids:
  name: Kid devices
  entities:
    - person.dorothee
    - person.olivier
    
pets:
  name: Pet Devices
  entities:
    - person.sven
    - person.gustaf
    - person.loki
