goat4sale:
  alias: Goat 4 Sale
  sequence:
  - service: media_extractor.play_media
    data:
      entity_id: media_player.chambre_principale
      media_content_type: 'video/youtube'
      media_content_id: 'https://www.youtube.com/watch?v=DoM6IhfY8No'
